version: "3.8"

services:
  wordpress:
    image: wordpress
    container_name: ramarmalia_wordpress # Nama container untuk WordPress
    restart: always
    ports:
      - "8888:80" # Port untuk WordPress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dewo
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html # Menyimpan data WordPress di direktori lokal
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ramarmalia_db
    restart: always
    ports:
      - "3376:3306" # Mengekspos port MySQL ke host
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: dewo
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./db:/var/lib/mysql # Menyimpan data MySQL di direktori lokal
